#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Kodaira Takumi
# SPDX-License-Identifier: BSD-3-Clause 

import sys

ans = 0

for line in sys.stdin:
    try:
        print("+" + str(line),end="")
        ans += int(line)
    except:
        print("+" + str(line),end="")
        ans += float(line)

print("=" + str(ans))


